In [3]:
df = pd.read_csv("/home/scott/Documents/GIT/data-science/crim_pris_age.tsv", sep="\t")

In [6]:
df['split'] = df[df.columns[0]].str.split(",")

In [7]:
df

,"age,sex,unit,geo\time",2015,2014,2013,2012,2011,2010,2009,2008,split
0,"ADULT,F,NR,AL",121,109,89,82,84,96,113,101,"[ADULT, F, NR, AL]"
1,"ADULT,F,NR,AT",498,501,538,568,564,516,460,396,"[ADULT, F, NR, AT]"
2,"ADULT,F,NR,BA",86,60,56,:,38,60,:,:,"[ADULT, F, NR, BA]"
3,"ADULT,F,NR,BE",525,:,456,440,437,411,389,441,"[ADULT, F, NR, BE]"
4,"ADULT,F,NR,BG",245,258,263,307,289,291,240,290,"[ADULT, F, NR, BG]"
5,"ADULT,F,NR,CH",355,315,347,306,301,319,345,298,"[ADULT, F, NR, CH]"
6,"ADULT,F,NR,CY",31,30,25,43,35,45,31,42,"[ADULT, F, NR, CY]"
7,"ADULT,F,NR,CZ",1430,1164,954,1446,1480,1282,999,1079,"[ADULT, F, NR, CZ]"
8,"ADULT,F,NR,DE",3609,3639,3797,3943,3927,3845,3857,3930,"[ADULT, F, NR, DE]"
9,"ADULT,F,NR,DK",118,145,189,149,164,183,178,155,"[ADULT, F, NR, DK]"
10,"ADULT,F,NR,EE",153,:,154,162,181,193,149,190,"[ADULT, F, NR, EE]"
11,"ADULT,F,NR,EL",488,561,648,557,562,577,554,744,"[ADULT, F, NR, EL]"
12,"ADULT,F,NR,ES",4623,4874,4925,5068,5157,5652,6076,5950,"[ADULT, F, NR, ES]"
13,"ADULT,F,NR,FI",228,237,253,219,228,245,238,218,"[ADULT, F, NR, FI]"
14,"ADULT,F,NR,FR",2119,2073,2131,2180,2167,1927,2021,2093,"[ADULT, F, NR, FR]"
15,"ADULT,F,NR,HR",160,182,188,202,245,228,218,209,"[ADULT, F, NR, HR]"
16,"ADULT,F,NR,HU",1235,1332,1336,1225,1216,1009,989,923,"[ADULT, F, NR, HU]"
17,"ADULT,F,NR,IE",115,120,121,122,122,138,123,111,"[ADULT, F, NR, IE]"
18,"ADULT,F,NR,IS",:,:,5,13,8,8,7,9,"[ADULT, F, NR, IS]"
19,"ADULT,F,NR,IT",2107,2304,2694,2804,2808,2930,2751,2526,"[ADULT, F, NR, IT]"
20,"ADULT,F,NR,LI",3,4,3,3,3,5,9,4,"[ADULT, F, NR, LI]"
21,"ADULT,F,NR,LT",295,377,428,435,417,414,367,355,"[ADULT, F, NR, LT]"
22,"ADULT,F,NR,LU",40,25,31,31,36,23,38,32,"[ADULT, F, NR, LU]"
23,"ADULT,F,NR,LV",355,343,347,416,416,421,402,380,"[ADULT, F, NR, LV]"
24,"ADULT,F,NR,ME",35,31,19,53,37,59,39,18,"[ADULT, F, NR, ME]"
25,"ADULT,F,NR,MK",:,:,:,:,50,55,55,:,"[ADULT, F, NR, MK]"
26,"ADULT,F,NR,MT",39,37,44,47,35,34,28,29,"[ADULT, F, NR, MT]"
27,"ADULT,F,NR,NL",489,662,673,712,789,872,896,940,"[ADULT, F, NR, NL]"
28,"ADULT,F,NR,NO",:,:,200,248,252,221,211,192,"[ADULT, F, NR, NO]"
29,"ADULT,F,NR,PL",2336,2484,2591,2638,2456,2515,2434,2455,"[ADULT, F, NR, PL]"
...,...,...,...,...,...,...,...,...,...,...
686,"TOTAL,T,P_HTHAB,EE",214.70,230.58,235.73,247.96,255.70,254.48,266.14,273.15,"[TOTAL, T, P_HTHAB, EE]"
687,"TOTAL,T,P_HTHAB,EL",89.48,107.97,115.35,112.53,112.19,111.06,102.43,110.13,"[TOTAL, T, P_HTHAB, EL]"
688,"TOTAL,T,P_HTHAB,ES",132.65,139.78,142.88,146.52,151.01,159.03,164.53,161.07,"[TOTAL, T, P_HTHAB, ES]"
689,"TOTAL,T,P_HTHAB,FI",57.29,57.75,60.72,61.21,60.80,62.86,67.38,66.60,"[TOTAL, T, P_HTHAB, FI]"
690,"TOTAL,T,P_HTHAB,FR",100.29,100.50,102.25,101.98,99.70,93.64,94.76,97.26,"[TOTAL, T, P_HTHAB, FR]"
691,"TOTAL,T,P_HTHAB,HR",79.07,88.61,102.11,110.88,118.51,120.04,113.49,109.79,"[TOTAL, T, P_HTHAB, HR]"
692,"TOTAL,T,P_HTHAB,HU",177.05,181.12,180.05,172.97,172.35,163.05,153.84,146.76,"[TOTAL, T, P_HTHAB, HU]"
693,"TOTAL,T,P_HTHAB,IE",81.12,82.01,89.04,93.55,92.24,94.91,85.55,78.16,"[TOTAL, T, P_HTHAB, IE]"
694,"TOTAL,T,P_HTHAB,IS",:,:,47.23,47.88,47.10,52.58,46.34,44.38,"[TOTAL, T, P_HTHAB, IS]"
695,"TOTAL,T,P_HTHAB,IT",87.85,90.07,106.97,112.98,115.09,117.02,111.18,101.08,"[TOTAL, T, P_HTHAB, IT]"
696,"TOTAL,T,P_HTHAB,LI",141.84,142.75,184.59,164.50,196.41,211.73,418.67,220.61,"[TOTAL, T, P_HTHAB, LI]"
697,"TOTAL,T,P_HTHAB,LT",251.77,293.40,311.62,323.91,324.97,290.87,271.84,249.02,"[TOTAL, T, P_HTHAB, LT]"
698,"TOTAL,T,P_HTHAB,LU",122.74,113.88,122.15,126.89,124.45,135.64,142.25,157.50,"[TOTAL, T, P_HTHAB, LU]"
699,"TOTAL,T,P_HTHAB,LV",221.99,237.08,253.78,299.15,316.25,319.74,326.19,298.75,"[TOTAL, T, P_HTHAB, LV]"
700,"TOTAL,T,P_HTHAB,ME",181.80,180.69,171.37,214.57,214.25,235.38,242.89,197.55,"[TOTAL, T, P_HTHAB, ME]"
701,"TOTAL,T,P_HTHAB,MT",131.60,136.58,145.95,140.10,140.73,141.05,120.22,162.32,"[TOTAL, T, P_HTHAB, MT]"
702,"TOTAL,T,P_HTHAB,NL",64.20,70.91,75.81,80.53,83.87,86.68,87.13,89.06,"[TOTAL, T, P_HTHAB, NL]"
703,"TOTAL,T,P_HTHAB,NO",:,:,76.59,81.27,78.57,73.36,69.59,73.40,"[TOTAL, T, P_HTHAB, NO]"
704,"TOTAL,T,P_HTHAB,PL",188.85,206.11,210.61,224.52,217.62,216.64,224.85,222.95,"[TOTAL, T, P_HTHAB, PL]"
705,"TOTAL,T,P_HTHAB,PT",138.54,136.16,138.60,131.61,122.53,111.97,106.85,102.40,"[TOTAL, T, P_HTHAB, PT]"
706,"TOTAL,T,P_HTHAB,RO",142.59,151.18,167.00,158.33,143.34,131.60,130.70,127.02,"[TOTAL, T, P_HTHAB, RO]"
707,"TOTAL,T,P_HTHAB,RS",141.46,143.95,139.68,141.70,152.66,153.44,149.63,131.71,"[TOTAL, T, P_HTHAB, RS]"
708,"TOTAL,T,P_HTHAB,SE",56.87,59.12,59.89,66.39,70.83,73.29,78.71,77.02,"[TOTAL, T, P_HTHAB, SE]"
709,"TOTAL,T,P_HTHAB,SI",67.82,73.84,66.06,66.99,62.09,66.00,67.16,65.56,"[TOTAL, T, P_HTHAB, SI]"
710,"TOTAL,T,P_HTHAB,SK",182.85,185.01,180.25,200.77,195.18,186.09,173.08,151.90,"[TOTAL, T, P_HTHAB, SK]"
711,"TOTAL,T,P_HTHAB,TR",:,206.98,192.36,182.03,174.44,166.50,162.67,:,"[TOTAL, T, P_HTHAB, TR]"
712,"TOTAL,T,P_HTHAB,UKC-L",146.42,146.35,144.27,150.59,150.95,151.46,148.69,149.54,"[TOTAL, T, P_HTHAB, UKC-L]"
713,"TOTAL,T,P_HTHAB,UKM",144.57,144.84,148.38,151.84,154.87,149.68,152.66,150.93,"[TOTAL, T, P_HTHAB, UKM]"
714,"TOTAL,T,P_HTHAB,UKN",78.34,93.02,98.32,92.47,92.45,81.43,85.38,87.16,"[TOTAL, T, P_HTHAB, UKN]"
715,"TOTAL,T,P_HTHAB,XK",:,:,:,:,80.32,:,:,:,"[TOTAL, T, P_HTHAB, XK]"