In [63]:
import requests
from bs4 import BeautifulSoup

# Let's now pull the average monthy daytime temperatures from wikipedia
r = requests.get("https://en.wikipedia.org/wiki/Berlin#Climate")
soup = BeautifulSoup(r.text, "lxml")
#table = soup.find("th", text="Climate data for Berlin- Tempelhof (1971–2000), extremes (1876– 2015) (Source: DWD)")

table = soup.findAll("table", {"class" : "wikitable collapsible"})[0]

df = pd.read_html(str(table), skiprows=1, index_col=0)[0]

df.columns = df.loc['Month'].tolist()
df.drop("Month", axis=0, inplace=True)
df.index.name = ""

df

import re
df.loc["Average high °C (°F)"] = df.loc["Average high °C (°F)"].apply(lambda x: re.findall("(.+)\s\(", x))
df.loc["Average high °C (°F)"] = df.loc["Average high °C (°F)"].apply(lambda x: float(x[0]))

df.loc["Average high °C (°F)"]

In [83]:
df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Year
,,,,,,,,,,,,,
Record high °C (°F),15.5 (59.9),18.7 (65.7),24.8 (76.6),31.3 (88.3),35.5 (95.9),35.9 (96.6),38.1 (100.6),38.0 (100.4),34.2 (93.6),28.1 (82.6),20.5 (68.9),16.0 (60.8),38.1 (100.6)
Average high °C (°F),3.3 (37.9),5.0 (41),9.0 (48.2),15.0 (59),19.6 (67.3),22.3 (72.1),25.0 (77),24.5 (76.1),19.3 (66.7),13.9 (57),7.7 (45.9),3.7 (38.7),14.02 (57.24)
Daily mean °C (°F),0.6 (33.1),1.4 (34.5),4.8 (40.6),8.9 (48),14.3 (57.7),17.1 (62.8),19.2 (66.6),18.9 (66),14.5 (58.1),9.7 (49.5),4.7 (40.5),2.0 (35.6),9.67 (49.42)
Average low °C (°F),−1.9 (28.6),−1.5 (29.3),1.3 (34.3),4.2 (39.6),9.0 (48.2),12.3 (54.1),14.3 (57.7),14.1 (57.4),10.6 (51.1),6.4 (43.5),2.2 (36),−0.4 (31.3),5.88 (42.59)
Record low °C (°F),−23.1 (−9.6),−26.0 (−14.8),−16.5 (2.3),−8.1 (17.4),−4.0 (24.8),1.5 (34.7),5.4 (41.7),3.5 (38.3),−1.5 (29.3),−9.6 (14.7),−16.0 (3.2),−20.5 (−4.9),−26.0 (−14.8)
Average rainfall mm (inches),42.3 (1.665),33.3 (1.311),40.5 (1.594),37.1 (1.461),53.8 (2.118),68.7 (2.705),55.5 (2.185),58.2 (2.291),45.1 (1.776),37.3 (1.469),43.6 (1.717),55.3 (2.177),570.7 (22.469)
Average rainy days (≥ 1.0 mm),10.0,8.0,9.1,7.8,8.9,7.0,7.0,7.0,7.8,7.6,9.6,11.4,101.2
Mean monthly sunshine hours,46.5,73.5,120.9,159.0,220.1,222.0,217.0,210.8,156.0,111.6,51.0,37.2,1625.6
"Source: World Meteorological Organization (UN),[66] HKO[67][68]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df.l

Month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Year
0,,,,,,,,,,,,,
Record high °C (°F),15.5 (59.9),18.7 (65.7),24.8 (76.6),31.3 (88.3),35.5 (95.9),35.9 (96.6),38.1 (100.6),38.0 (100.4),34.2 (93.6),28.1 (82.6),20.5 (68.9),16.0 (60.8),38.1 (100.6)
Average high °C (°F),3.3 (37.9),5.0 (41),9.0 (48.2),15.0 (59),19.6 (67.3),22.3 (72.1),25.0 (77),24.5 (76.1),19.3 (66.7),13.9 (57),7.7 (45.9),3.7 (38.7),14.02 (57.24)
Daily mean °C (°F),0.6 (33.1),1.4 (34.5),4.8 (40.6),8.9 (48),14.3 (57.7),17.1 (62.8),19.2 (66.6),18.9 (66),14.5 (58.1),9.7 (49.5),4.7 (40.5),2.0 (35.6),9.67 (49.42)
Average low °C (°F),−1.9 (28.6),−1.5 (29.3),1.3 (34.3),4.2 (39.6),9.0 (48.2),12.3 (54.1),14.3 (57.7),14.1 (57.4),10.6 (51.1),6.4 (43.5),2.2 (36),−0.4 (31.3),5.88 (42.59)
Record low °C (°F),−23.1 (−9.6),−26.0 (−14.8),−16.5 (2.3),−8.1 (17.4),−4.0 (24.8),1.5 (34.7),5.4 (41.7),3.5 (38.3),−1.5 (29.3),−9.6 (14.7),−16.0 (3.2),−20.5 (−4.9),−26.0 (−14.8)
Average rainfall mm (inches),42.3 (1.665),33.3 (1.311),40.5 (1.594),37.1 (1.461),53.8 (2.118),68.7 (2.705),55.5 (2.185),58.2 (2.291),45.1 (1.776),37.3 (1.469),43.6 (1.717),55.3 (2.177),570.7 (22.469)
Average rainy days (≥ 1.0 mm),10.0,8.0,9.1,7.8,8.9,7.0,7.0,7.0,7.8,7.6,9.6,11.4,101.2
Mean monthly sunshine hours,46.5,73.5,120.9,159.0,220.1,222.0,217.0,210.8,156.0,111.6,51.0,37.2,1625.6
"Source: World Meteorological Organization (UN),[66] HKO[67][68]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df.index.name

0